CourseNotFound = "Course Not Found", False, 404
StudentNotFound = "Student Not Found", False, 404
UserNotFound = "Student Not Found", False, 404
TimeslotNotFound =  "Timeslot Not Found", False, 404
IncorrectCredentials = "Incorrect Username or Password", False, 401
MissingCredentials = "Missing Username and/or Password. ", False, 404
InvalidSessionToken = "Invalid session token", False, 404
UnauthorizedAccess = "Unauthorized Access ", False, 401
MissingTimes = "Must provide both [start_time] and [end_time].", False, 404
MissingTitle = "Must provide [title].", False, 404
InvalidTimeRange = "Invalid time range. ", False, 404
StudentInQueue = "Already in Queue", False, 400